jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('create/',views.CreateJob.as_view(),name='create'),
    path('joblist/',views.JobList.as_view(),name='list'),
    path('dashboard/',views.JobDashboard.as_view(),name='dashboard'),
    path('plots/',views.JobPlots.as_view(),name='plots'),
    path('<int:pk>/',views.JobDetail.as_view(),name='detail'),
    path('<int:pk>/edit/',views.JobUpdate.as_view(),name='job_edit'),
    path('<int:pk>/remove/',views.JobDelete.as_view(),name='job_remove'),
    path('filter/',views.job_list_filter,name='filter'),
]

jobtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('siteadmin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about/',views.AboutPage.as_view(),name='about'),
    path('account/',include('account.url',namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
    path('logout_success/',views.LogOut.as_view(),name='logout_success'),
    path('jobs/',include('jobs.urls',namespace='jobs')),
]

templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>Add a job or internship application</h3>
  <div class="row frontpage-row">
    <p class=' description'>Easily add new job applications.</p>
    <div class="row">
      <a href="{% static "images/newapp.png" %}" target="_blank"><img style="width:50%;border:1px solid black" src="{% static "images/newapp.png" %}" alt=""></a>
    </div>
  </div>
</div>
<hr>
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>Keep track of all your applications</h3>
  <div class="row frontpage-row">
    <p class='description'>Keep all your applications in one place. Sort by when you applied or by application status.</p>
    <a href="{% static "images/joblist.png" %}" target="_blank"><img style="width:50%;border:1px solid black" src="{% static "images/joblist.png" %}" alt=""></a>
  </div>
</div>
<hr>
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>Add detailed notes as you progress</h3>
  <div class="row frontpage-row">
    <p class=' description'>Update your applications throughout the recruitment process. Update each job as necessary and add detailed notes for future reference.</p>
    <a href="{% static "images/update.png" %}" target="_blank"><img style="width:50%;border:1px solid black" src="{% static "images/update.png" %}" alt=""></a>
  </div>
</div>
<hr>
<div class="footer">
  <a href="https://sites.google.com/view/tommyyong" class='col-lg-8 col-md-8 col-sm-4'>Tommy Yong</a>
  <a href="https://www.linkedin.com/in/tommy-yong-107b15101/" class='col-lg-2 col-md-2 col-sm-4'>LinkedIn</a>
  <a href="https://github.com/tommyyong93" class='col-lg-2 col-md-2 col-sm-4'>GitHub</a>
</div>
{% endblock %}
<script src="https://www.gstatic.com/charts/loader.js"></script>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Job Tracker</title>
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Fonts  -->
    <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap" rel="stylesheet">
    <!-- Custom CSS  -->
    <link rel="stylesheet" href="{% static 'jobtracker/css/master.css' %}">
    <!-- Font Awesome  -->
    <script src="https://kit.fontawesome.com/5f6b1eefa2.js" crossorigin="anonymous"></script>
    <!-- MediumEditor  -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- Master CSS  -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <!-- Google Charts  -->
    <script src="https://www.gstatic.com/charts/loader.js"></script>
  </head>

  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">Job Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse bg-light" id="navbarSupportedContent">
          <ul class='nav navbar-nav navbar-right ml-auto'>
            {% if user.is_authenticated %}
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'jobs:create' %}">New Job Application</a>
            </li>
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'jobs:filter' %}">Applied Jobs</a>
            </li>
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'jobs:dashboard' %}">Dashboard</a>
            </li>
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'jobs:plots' %}">Sankey</a>
            </li>
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'accounts:login' %}">Log In</a>
            </li>
            <li class='nav-item'>
              <a class='nav-link' href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>
    <!-- jQuery, Popper.js, bootstrap.js  -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="header container">
  <h1 class='welcome_title'>Welcome to Job Tracker!</h1>
  <h2 class='welcome_subtitle'>Organize your job and internship applications all in one place!</h2>
</div>
<hr class='bg-light'>
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>No more sifting through your inbox!</h3>
  <div class="row">
    <img class='col-3' src="{% static "images/envelope.svg" %}" alt="">
    <p class='col-9 description'>Tired of searching through your inbox to find if you applied for a particular position? Keep all your job and internship applications all in one place.
      The Job Tracker platform allows you to seemlessly add new job applications and keep them all in one place.</p>
  </div>
</div>
<hr class='bg-light'>
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>Keep track of when you applied!</h3>
  <div class="row">
    <p class='col-9 description'>Forgetting when you applied to a particular position? Want to know how long it's been since you've been contacted by a recruiter?
      Has it been long enough to warrant a follow-up email? Keep all the dates of your applications in one place. </p>
    <img class='col-3' src="{% static "images/month.svg" %}" alt="">
  </div>
</div>
<hr class='bg-light'>
<div class="row frontpage-row">
  <h3 class='frontpage subtitle'>Add detailed notes as you progress!</h3>
  <div class="row">
    <img class='col-3' src="{% static "images/seo-and-web.svg" %}" alt="">
    <p class='col-9 description'>Add notes to each job application! Use these notes to prepare for online assessments, to add details during your interview or to
      add anything else that you need to remember!</p>
  </div>
</div>
<p style="font-size:0.5em">"Icons made by Freepik from www.flaticon.com"</p>
<hr class='bg-light'>
<div class="footer">
  <a href="https://www.tommyyong.com" class='col-lg-8 col-md-8 col-sm-4'>Tommy Yong</a>
  <a href="https://www.linkedin.com/in/tommy-yong-107b15101/" class='col-lg-2 col-md-2 col-sm-4'>LinkedIn</a>
  <a href="https://github.com/tommyyong93" class='col-lg-2 col-md-2 col-sm-4'>GitHub</a>
</div>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}
{% block content %}
<h1 class='subpage-title'>You are successfully logged out, thanks for visiting!</h1>
{% endblock %}