jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('create/',views.CreateJob.as_view(),name='create'),
    path('joblist/',views.JobList.as_view(),name='list'),
    path('dashboard/',views.JobDashboard.as_view(),name='dashboard'),
    path('plots/',views.JobPlots.as_view(),name='plots'),
    path('<int:pk>/',views.JobDetail.as_view(),name='detail'),
    path('<int:pk>/edit/',views.JobUpdate.as_view(),name='job_edit'),
    path('<int:pk>/remove/',views.JobDelete.as_view(),name='job_remove'),
    path('filter/',views.job_list_filter,name='filter'),
]

jobtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('siteadmin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about/',views.AboutPage.as_view(),name='about'),
    path('account/',include('account.url',namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
    path('logout_success/',views.LogOut.as_view(),name='logout_success'),
    path('jobs/',include('jobs.urls',namespace='jobs')),
]

jobs/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.db.models import Q
# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

# Gets jobs which are under status 'online'
class OnlineManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(date_online_assessment__isnull = False)
                                            | Q(status__iexact='Online Assessment 1')
                                            | Q(status__iexact='Online Assessment 2')
                                            | Q(status__iexact='Online Assessment 3'))

# Gets jobs which are under status 'phone'
class PhoneManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(date_phone_interview__isnull = False)
                                            | Q(status__iexact='Phone Interview 1')
                                            | Q(status__iexact='Phone Interview 2'))

# Gets jobs which are under status 'video'
class VideoManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(date_video_interview__isnull = False)
                                            | Q(status__iexact='Video Interview 1')
                                            | Q(status__iexact='Video Interview 2'))

# Gets jobs which are under status 'onsite'
class OnsiteManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(date_onsite_interview__isnull = False)
                                            | Q(status__iexact='Onsite Interview'))

# Gets jobs which are under status 'final decision'
class FinalDecisionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(date_final_decision__isnull = False)
                                            | Q(status__iexact='Offer')
                                            | Q(status__iexact='Accepted Offer')
                                            | Q(status__iexact='Declined Offer')
                                            )

# Gets jobs which are under status 'rejection'
class RejectionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(status__iexact='Rejection')
                                            |Q(date_rejected__isnull=False))

# Gets jobs which are under status 'no response'
class NoResponseManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(Q(status__iexact='No Response'))

# Job model
class Job(models.Model):
    # Categories for status
    STATUS = (('Applied','Applied'),
    ('Online Assessment 1','Online Assessment 1'),
    ('Online Assessment 2','Online Assessment 2'),
    ('Online Assessment 3','Online Assessment 3'),
    ('Phone Interview 1','Phone Interview 1'),
    ('Phone Interview 2','Phone Interview 2'),
    ('Video Interview 1','Video Interview 1'),
    ('Video Interview 2','Video Interview 2'),
    ('Onsite Interview','Onsite Interview'),
    ('Offer','Offer'),
    ('Rejection','Rejection'),
    ('Accepted Offer','Accepted Offer'),
    ('Declined Offer','Declined Offer'),
    ('No Response','No Response'))

    user = models.ForeignKey(User,related_name='jobs',on_delete=models.CASCADE)
    name = models.CharField(max_length=1000)
    slug = models.SlugField(allow_unicode=True)
    status = models.CharField(blank=True,choices=STATUS,max_length=30)
    location = models.CharField(blank=True,max_length=255)
    date_applied = models.DateField(null=True)
    date_online_assessment = models.DateField(null=True)
    date_phone_interview = models.DateField(null=True)
    date_video_interview = models.DateField(null=True)
    date_onsite_interview = models.DateField(null=True)
    date_final_decision = models.DateField(null=True)
    date_rejected = models.DateField(null=True)
    notes = models.TextField(blank=True,default='')
    notes_html = models.TextField(editable=False,default='',blank=True,null=True)

    objects = models.Manager()
    online_jobs = OnlineManager()
    phone_jobs = PhoneManager()
    video_jobs = VideoManager()
    onsite_jobs = OnsiteManager()
    final_jobs = FinalDecisionManager()
    rejection_jobs = RejectionManager()
    no_response = NoResponseManager()

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.notes_html = misaka.html(self.notes)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['date_applied']
        unique_together = ['user','name']

jobs/forms.py
from django import forms
from django.forms import ModelForm
from .models import Job
from django.core import validators

# Job form to allow use of widgets
class JobForm(ModelForm):

    date_applied = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model = Job
        fields = ('name','status','location','date_applied','notes')
        widgets = {
            'notes': forms.Textarea(attrs={'class':'editable medium-editor-textarea job_description'})
        }

# Update job form to allow use of widgets
class UpdateJobForm(ModelForm):

    date_applied = forms.DateField(widget=forms.SelectDateWidget())
    date_online_assessment = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))
    date_phone_interview = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))
    date_video_interview = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))
    date_onsite_interview = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))
    date_final_decision = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))
    date_rejected = forms.DateField(required=False,widget=forms.SelectDateWidget(empty_label="---"))

    class Meta:
        model = Job
        fields = ('location','status','date_applied','date_online_assessment',
        'date_phone_interview','date_video_interview','date_onsite_interview',
        'date_final_decision','date_rejected','notes')
        widgets ={
            'notes': forms.Textarea(attrs={'class':'editable medium-editor-textarea job_description'})
        }

jobs/views.py
from django.core import serializers
from django import forms
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import Http404, JsonResponse
from django.contrib import messages
from braces.views import SelectRelatedMixin
from jobs.models import Job
from . import models
from .forms import JobForm, UpdateJobForm
from .filters import JobFilter
import django_filters

from django.contrib.auth import get_user_model
User = get_user_model()

# View for creating a new job
class CreateJob(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    login_url = 'login'
    def get_redirect_url(self,*args,**kwargs):
        return reverse('home')

    model = Job
    form_class = JobForm

    def get_success_url(self):
        return reverse('jobs:filter')

    def form_valid(self,form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

# View using filter use this instead of JobList
def job_list_filter(request):
    queryset = queryset=User.objects.prefetch_related("jobs").get(
        username__iexact=request.user.get_username()
    )
    print(queryset)
    filter = JobFilter(request.GET,queryset=queryset.jobs.all())
    return render(request, 'jobs/job_filter.html', {'filter': filter})

# View for the job list (applied jobs)
class JobList(LoginRequiredMixin,SelectRelatedMixin,generic.ListView):
    login_url = 'login'
    model = Job
    template_name = 'jobs/job_list.html'
    select_related = ('user',)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["job_user"] = self.job_user
        return context

    def get_queryset(self):
        try:
            self.job_user = User.objects.prefetch_related("jobs").get(
                username__iexact=self.request.user.get_username()
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.job_user.jobs.all()

# View for one job -- includes update and delete button
class JobDetail(LoginRequiredMixin,SelectRelatedMixin,generic.DetailView):
    model = Job
    select_related = ('user',)
    login_url = 'login'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.request.user.get_username())

# View for updating job
class JobUpdate(LoginRequiredMixin,SelectRelatedMixin,generic.UpdateView):
    login_url = 'login'
    select_related = ('user',)
    template_name = 'jobs/job_edit.html'
    form_class = UpdateJobForm
    model = Job

    def get_success_url(self):
        return reverse_lazy('jobs:filter')

# View for deleting job
class JobDelete(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    login_url = 'login'
    model = Job
    select_related = ('user',)

    def get_success_url(self):
        return reverse_lazy('jobs:filter')

# Dashboard view -- inlcudes more data in query set
class JobDashboard(LoginRequiredMixin,SelectRelatedMixin,generic.ListView):
    login_url = 'login'
    model = Job
    template_name = 'jobs/job_dashboard.html'
    select_related = ('user',)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["job_user"] = self.job_user
        context["online_jobs"] = self.online_jobs
        context["phone_jobs"] = self.phone_jobs
        context["video_jobs"] = self.video_jobs
        context["onsite_jobs"] = self.onsite_jobs
        context["final_jobs"] = self.final_jobs
        context["rejection_jobs"] = self.rejection_jobs
        context["no_response"] = self.no_response
        return context

    def get_queryset(self):
        try:
            self.job_user = User.objects.prefetch_related("jobs").get(
                username__iexact=self.request.user.get_username()
            )
            self.online_jobs = Job.online_jobs.all().filter(user=self.request.user)
            self.phone_jobs = Job.phone_jobs.all().filter(user=self.request.user)
            self.video_jobs = Job.video_jobs.all().filter(user=self.request.user)
            self.onsite_jobs = Job.onsite_jobs.all().filter(user=self.request.user)
            self.final_jobs = Job.final_jobs.all().filter(user=self.request.user)
            self.rejection_jobs = Job.rejection_jobs.all().filter(user=self.request.user)
            self.no_response = Job.no_response.all().filter(user=self.request.user)
        except User.DoesNotExist:
            raise Http404
        else:
            return self.job_user.jobs.all()

# View for plots - data has been serialized to be used in js
class JobPlots(LoginRequiredMixin,SelectRelatedMixin,generic.ListView):
    login_url = 'login'
    model = Job
    template_name = 'jobs/job_plots.html'
    select_related = ('user',)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        JSONSerializer = serializers.get_serializer("json")
        json_serializer = JSONSerializer()
        json_serializer.serialize(self.online_jobs)
        context["job_user"] = self.job_user
        context["online_jobs"] = self.online_jobs
        context["phone_jobs"] = self.phone_jobs
        context["video_jobs"] = self.video_jobs
        context["onsite_jobs"] = self.onsite_jobs
        context["final_jobs"] = self.final_jobs
        context["rejection_jobs"] = self.rejection_jobs
        context["no_response"] = self.no_response
        ### serialize querysets to use in javascript
        json_serializer.serialize(self.job_user.jobs.all())
        context['applied_jobs_dict'] = json_serializer.getvalue()
        json_serializer.serialize(self.online_jobs)
        context["online_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.phone_jobs)
        context["phone_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.video_jobs)
        context["video_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.onsite_jobs)
        context["onsite_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.final_jobs)
        context["final_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.rejection_jobs)
        context["rejection_jobs_dict"] = json_serializer.getvalue()
        json_serializer.serialize(self.no_response)
        context["no_response_dict"] = json_serializer.getvalue()
        return context

    def get_queryset(self):
        try:
            self.job_user = User.objects.prefetch_related("jobs").get(
                username__iexact=self.request.user.get_username()
            )
            self.online_jobs = Job.online_jobs.all().filter(user=self.request.user)
            self.phone_jobs = Job.phone_jobs.all().filter(user=self.request.user)
            self.video_jobs = Job.video_jobs.all().filter(user=self.request.user)
            self.onsite_jobs = Job.onsite_jobs.all().filter(user=self.request.user)
            self.final_jobs = Job.final_jobs.all().filter(user=self.request.user)
            self.rejection_jobs = Job.rejection_jobs.all().filter(user=self.request.user)
            self.no_response = Job.no_response.all().filter(user=self.request.user)
        except User.DoesNotExist:
            raise Http404
        else:
            return self.job_user.jobs.all()

jobs/templates/jobs/_job.html
<div class="col-12 col">
  <div class="card job-card">
    <div class="header">
      <h5 class='card-header'>
        <a href="{% url 'jobs:detail' job.pk %}">{{ job.name }}</a>
        <a data-toggle="collapse" href={{"#"|add:job.name}} role="button" aria-expanded="false" aria-controls={{job.name}}><svg class="bi bi-chevron-expand" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3.646 9.146a.5.5 0 0 1 .708 0L8 12.793l3.646-3.647a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 0-.708zm0-2.292a.5.5 0 0 0 .708 0L8 3.207l3.646 3.647a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 0 0 0 .708z" />
          </svg>
        </a>
      </h5>
    </div>
    <div class="card-body collapse job-collapse" id={{job.name}}>
      {% if job.status == 'Applied' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-warning'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Online Assessment 1' or job.status == 'Online Assessment 2' or job.status == 'Online Assessment 3' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-info'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Phone Interview 1' or job.status == 'Phone Interview 2' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-info'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Video Interview 1' or job.status == 'Video Interview 2' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-info'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Onsite Interview' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-info'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Offer' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-success'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Rejection' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-danger'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Accepted Offer' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-success'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'Decline Offer' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-secondary'>{{ job.status }}</span>
      </h6>
      {% elif job.status == 'No Response' %}
      <h6 class="card-subtitle mb-2">Status: <span class='text-muted'>{{ job.status }}</span>
      </h6>
      {% endif %}
      {% if job.location != "" and job.location != "<p><br></p>" %}
      <h6 class="card-subtitle mb-2">Location: <span class='text-muted'>{{ job.location }}</span>
      </h6>
      {% endif %}
      <h6 class="card-subtitle mb-2 text-muted">Date Applied: {{ job.date_applied }}</h6>
      {% if job.date_online_assessment != null %}
      <h6 class="card-subtitle mb-2 text-muted">Date Online Assessment: {{ job.date_online_assessment }}</h6>
      {% endif %}
      {% if job.date_phone_interview != null %}
      <h6 class="card-subtitle mb-2 text-muted">Date Phone Interview: {{ job.date_phone_interview }}</h6>
      {% endif %}
      {% if job.date_video_interview != null %}
      <h6 class="card-subtitle mb-2 text-muted">Date Video Interview: {{ job.date_video_interview }}</h6>
      {% endif %}
      {% if job.date_onsite_interview != null %}
      <h6 class="card-subtitle mb-2 text-muted">Date Onsite Interview: {{ job.date_onsite_interview }}</h6>
      {% endif %}
      {% if job.date_final_decision != null %}
      <h6 class="card-subtitle mb-2 text-muted">Date Final Decision: {{ job.date_final_decision }}</h6>
      {% endif %}
      {% if job.notes != null and job.notes != "<p><br></p>" %}
      <p>{{job.notes_html|safe}}</p>
      {% endif %}
    </div>
  </div>
</div>

jobs/templates/jobs/job_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block prejob %}{% endblock %}
    {% block jobcontent %}{% endblock %}
    {% block postjob %}{% endblock %}
  </div>
</div>
{% endblock %}

jobs/templates/jobs/job_confirm_delete.html
{% extends 'jobs/job_base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete your job application at {{ object }}?</p>
  <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock %}

jobs/templates/jobs/job_dashboard.html
{% extends "jobs/job_base.html" %}
{% load bootstrap4 %}
{% block jobcontent %}
{% load static %}
<script type="text/javascript" src="{% static 'jobtracker/js/plots.js' %}"></script>
<div class="container">
  {% if user.jobs.count == 0 %}
  <h1 class='subpage-title'>You have no job applications yet!</h1>
  <h2 class='subpage-title'>Click <a href="{% url 'jobs:create' %}">here</a> to create a new application!</h2>
  {% else %}
  {% endif %}
  {% if user.jobs.count != 0  %}
  <h1 class='subpage-title'>Dashboard</h1>
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-warning'>Job Applications <span class='badge badge-warning' id='jobCount'>{{ user.jobs.count }}</span></h1>
    </div>
    {% endif %}
  </div>
  {% if online_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-info'>Online Assessments <span class='badge badge-info' id='onelineAssessments'>{{ online_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in online_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a>, date of online assessment: {{job.date_online_assessment}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if phone_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-info'>Phone Interviews <span class='badge badge-info'>{{ phone_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in phone_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a>, date of phone interview: {{job.date_phone_interview}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if video_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-info'>Video Interviews <span class='badge badge-info'>{{ video_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in video_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a>, date of video interview: {{job.date_video_interview}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if onsite_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-info'>Onsite Interviews <span class='badge badge-info'>{{ onsite_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in onsite_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a>, date of onsite interview: {{job.date_onsite_interview}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if final_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-success'>Final Decisions <span class='badge badge-success'>{{ final_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in final_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a>, {{job.status}}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if rejection_jobs.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-danger'>Rejections <span class='badge badge-danger'>{{ rejection_jobs.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in rejection_jobs %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  {% if no_response.count != 0 %}
  <div class="card dash-card">
    <div class="card-header">
      <h1 class='text-danger'>No Response <span class='badge badge-danger'>{{ no_response.count }}</span></h1>
    </div>
    <div class="card-text">
      <ul>
        {% for job in no_response %}
        <li><a href="{% url 'jobs:detail' job.pk %}">{{job.name}}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

jobs/templates/jobs/job_detail.html
{% extends "jobs/job_base.html" %}
{% block prejob %}
<div class="container">
  <h1 class='subpage-title'>{{job.name}}</h1>
  <div class="col-12">
    {% include "jobs/_job.html" %}
    <div class="card-body">
      <a href="{% url 'jobs:job_edit' pk=job.pk %}" title="update" class="btn btn-simple">
        <span class="fa fa-edit text-info" aria-hidden="true"></span>
        <span class="icon-label text-info">Update</span>
      </a>
      <a href="{% url 'jobs:job_remove' pk=job.pk %}" title="delete" class="btn btn-simple">
        <span class="fa fa-remove text-danger" aria-hidden="true"></span>
        <span class="text-danger icon-label">Delete</span>
      </a>
    </div>
  </div>
</div>
{% endblock %}

jobs/templates/jobs/job_edit.html
{% extends "jobs/job_base.html" %}
{% load bootstrap4 %}
{% block jobcontent %}
<div class="container">
  <h1 class='subpage-title'>Update your job application at {{ job.name }}</h1>
  <div class="container">
    <form action="{% url 'jobs:job_edit' job.pk %}" method="POST" id='jobForm'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn-large" value="Submit">
    </form>
  </div>
</div>
<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

jobs/templates/jobs/job_filter.html
{% extends "jobs/job_base.html" %}
{% load bootstrap4 %}
{% load widget_tweaks %}
{% block content %}
<script type="text/javascript">
  function myFunction() {
    var x = document.getElementById("hideToggle");
    if (x.style.display === "none") {
      x.style.display = "flex";
    } else {
      x.style.display = "none";
    }
  }

  function update() {
    var form = document.getElementById('filterForm')
    form.submit()
  }
</script>
<div class="container">
  {% if user.jobs.count == 0 %}
  <h1 class='subpage-title'>You have no job applications yet!</h1>
  <h2 class='subpage-title'>Click <a href="{% url 'jobs:create' %}">here</a> to create a new application!</h2>
  {% else %}
  <h1 class='subpage-title'>Your Job List</h1>
  <button onclick="myFunction()" class='btn btn-secondary btn-sm'>Toggle Filter</button>
  <button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target=".job-collapse" aria-expanded="false" aria-controls="collase">Toggle Info</button>
  <hr>
  <div class="container filter-container" id='hideToggle'>
    <form action="" method="GET" id='filterForm'>
      {% csrf_token %}
      <div class="row">
        <div class="col-8">
          <div class='row'>
            <div class="form-group-manual col-6" onchange='update()'>
              {{ filter.form.name_contains.label_tag }}
              {{ filter.form.name_contains |add_class:"form-control name-contains" }}
            </div>
            <div class="form-group-manual col-6" onchange='update()'>
              {{ filter.form.name.label_tag }}
              {{ filter.form.name |add_class:"form-control name" }}
            </div>
          </div>
          <div class="row">
            <div class="form-group-manual col-6" onchange='update()'>
              {{ filter.form.status.label_tag }}
              {{ filter.form.status |add_class:"form-control status" }}
            </div>
            <div class="form-group-manual col-6" onchange='update()'>
              {{ filter.form.location.label_tag }}
              {{ filter.form.location |add_class:"form-control location" }}
            </div>
          </div>
        </div>
        <div class="col-4">
          <div class="form-group-manual" onchange='update()'>
            {{ filter.form.date_applied.label_tag }}
            {{ filter.form.date_applied |add_class:"form-control date_applied" }}
          </div>
        </div>
      </div>
      <input type="submit" hidden />
    </form>
  </div>
  {% endif %}
</div>
<br>
<div class="container col-12">
  {% for job in filter.qs %}
  {% include "jobs/_job.html" %}
  {% endfor %}
</div>
{% endblock %}

jobs/templates/jobs/job_form.html
{% extends "jobs/job_base.html" %}
{% load bootstrap4 %}
{% block jobcontent %}
<div class="container class='bg-light'">
  <h1 class='subpage-title'>Create a new job application!</h1>
  <div class="container">
    <form action="{% url 'jobs:create' %}" method="POST" id='jobForm'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
  </div>
</div>
<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

jobs/templates/jobs/job_list.html
{% extends "jobs/job_base.html" %}
{% block jobcontent %}
<div class="container">
  {% if user.jobs.count == 0 %}
  <h1 class='subpage-title'>You have no job applications yet!</h1>
  <h2 class='subpage-title'>Click <a href="{% url 'jobs:create' %}">here</a> to create a new application!</h2>
  {% else %}
  <h1 class='subpage-title'>Your Job List</h1>
  {% endif %}
</div>
{% if user.jobs.count != 0 %}
<div class="container">
  <div class="row sort">
    <a href="{% url 'jobs:list' %}">Sort by Date Applied</a>
    <a href="{% url 'jobs:name' %}">Sort by Name</a>
    <a href="{% url 'jobs:status' %}">Sort by Status</a>
  </div>
</div>
{% endif %}
<div class="col-12">
  {% for job in job_list  %}
  {% include "jobs/_job.html" %}
  {% endfor %}
</div>
{% endblock %}